Ponto Digital/Controllers/DashboardController.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Ponto_Digital.Models;
using Ponto_Digital.Repositorio;
using Ponto_Digital.ViewModel;

namespace Ponto_Digital.Controllers {
    public class DashboardController : Controller {
        ComentarioViewModel dados = new ComentarioViewModel ();
        ComentarioRepositorio comentarioRepositorio = new ComentarioRepositorio ();
        UsuarioRepositorio usuarioRepositorio = new UsuarioRepositorio();
        private const string SESSION_TIPO = "_TIPO";
        private const string SESSION_EMAIL = "_EMAIL";
        private const string SESSION_USUARIO = "_USUARIO";
        List<ComentarioModel> comentarios = new List<ComentarioModel>();
        List<ComentarioModel> aprovados = new List<ComentarioModel>();
        List<ComentarioModel> rejeitados = new List<ComentarioModel>();
        List<UsuarioModel> usuarios = new List<UsuarioModel>();
        List<ComentarioModel> listaComentariosRecentes = new List<ComentarioModel>();
        List<UsuarioModel> listaUsuariosRecentes = new List<UsuarioModel>();

        public IActionResult Index () {
            comentarios = comentarioRepositorio.ListarComentarios ();
            usuarios = usuarioRepositorio.ListarUsuarios();

            foreach(var item in comentarios){

            if(item.Status == "Aprovado"){
                    aprovados.Add(item);
                    }
            else if(item.Status == "Rejeitado"){
                    rejeitados.Add(item);
            }
            }
            comentarios.Reverse();
            usuarios.Reverse();
            
            int count = 0;
            foreach (var item in comentarios)
            { 
                if (count < 10)
                {
                    listaComentariosRecentes.Add(item);
                    count++;    
                }
            }
            count = 0;
            foreach (var item in usuarios)
            {
                if (count < 10)
                {
                    listaUsuariosRecentes.Add(item);
                    count++;
                }
            }

            ViewData["Controller"] = HttpContext.Session.GetString (SESSION_USUARIO);
            ViewData["Tipo"] = HttpContext.Session.GetString (SESSION_TIPO);
            ViewData["User"] = HttpContext.Session.GetString (SESSION_EMAIL);

            dados.QuantidadeAprovados = aprovados.Count;
            dados.QuantidadeRejeitados = rejeitados.Count;
            dados.QuantidadeUsuarios = usuarios.Count;
            dados.QuantidadeComentarios = comentarios.Count;

            dados.UltimosUsuarios = listaUsuariosRecentes;
            dados.UltimosComentarios = listaComentariosRecentes;
            
            return View (dados);
        }
    }
}

Ponto Digital/Controllers/FACController.cs
using Microsoft.AspNetCore.Mvc;

namespace Ponto_Digital.Controllers
{
    public class FACController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Ponto Digital/Views/Shared/_Erro.cshtml
@{
var tipo = (string) ViewData["Tipo"];
var user = (string) ViewData["User"];
}

<head>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/site.min.css" />
</head>

<main>
    <h2>@ViewData["Controller"] com sucesso!</h2>
</main>

Ponto Digital/Views/Shared/_Layout.cshtml
@{
var user = (string) ViewData["User"];
var tipo = (string) ViewData["Tipo"];
}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Ponto Digital</title>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/site.min.css" />
    
</head>
      <header>
        <div>
            <div class="boxe">
                <div class="container">
                    <div class="header-menu">
                        <button><img src="images/multiplication_x_u2715_icon_256x256.png" alt=""></button>
                    </div>
                    <nav>
                        <ul class="top-menu">
                            <li class="menu-items"><a asp-controller="Home" asp-action="Index">Home</a></li>
                            @if(string.IsNullOrEmpty(tipo)){

                            <li class="menu-items"> <a href='@Url.Action("Index","Home")#produto'>Funcionalidade</a> </li>
                            <li class="menu-items"> <a href='@Url.Action("Index","Home")#plano'>Planos</a> </li>
                            <li class="menu-items"> <a href='@Url.Action("Index","Home")#quemsomos'>Quem somos?</a> </li>
                            <li class="menu-items"> <a id="bt_FAC" asp-controller="FAC" asp-action="Index">FAC</a> </li>
                            <li class="menu-items"> <a href='@Url.Action("Index","Home")#contatos'>Contatos</a> </li>
                            
                            }else if(!string.IsNullOrEmpty(tipo)){
                            <li class="menu-items"> <a asp-controller="Dashboard" asp-action="Index">Dashboard</a> </li>
                            }
                        
                        @if (string.IsNullOrEmpty(user))
                        {
                            <li class="menu-items"> <a href='@Url.Action("Index","Home")#cadastro'>Cadastro</a> </li>
                            <li class="menu-items"><a href='@Url.Action("Index","Home")#cadastro'>Login</a> </li> 
                        }else{
                            <li class="menu-items"> <a href='@Url.Action("Index","Home")#comentarios'>Comentários</a> </li>
                            <li><a id="bt_logout" asp-controller="Home" asp-action="Logout">Logout</a></li>
                        }
                        </ul>
                    </nav>
                </div>
            </div>
            <div class="open-menu">
                <button><img src="https://cdn4.iconfinder.com/data/icons/wirecons-free-vector-icons/32/menu-alt-256.png"></button>
            </div>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>

            <script>

            </script>

            <div id="espa"></div>
            <div id="imag">
                <img src="images/banner ponto digital.png" alt="" class="imagem1">
                <img src="images/banner ponto digital - Copia.png" alt="" class="imagem1 w3-animate-top">
                <img src="images/banner ponto digital - Copia (2).png" alt="" class="imagem1">
            </div>
            <p id="logo">Ponto digital</p>
        </div>
    </header>
    <script>
    var myIndex = 0;
    carousel();

    function carousel() {
        var i;
        var x = document.getElementsByClassName("imagem1");
        for (i = 0; i < x.length; i++) {
            x[i].style.display = "none";
        }
        myIndex++;
        if (myIndex > x.length) { myIndex = 1 }
        x[myIndex - 1].style.display = "block";
        setTimeout(carousel, 5000);
    }
</script>

<body>
        @RenderBody()
     <footer id="contatos">
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3657.0658301189687!2d-46.65298398538392!3d-23.566079067650772!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x94ce59c8da0aa315%3A0xd59f9431f2c9776a!2sAv.+Paulista+-+Bela+Vista%2C+S%C3%A3o+Paulo+-+SP!5e0!3m2!1spt-BR!2sbr!4v1552524439656"
                width="100%" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
            <div id="rodape">

                <address>

                    <p>Agora vai!</p>
                    <p>pontodigital@gmail.com</p>
                    <p>Avenida Paulista</p>
                    <p>(11) 1234-5678</p>
                </address>

                <div id="oi">
                    <a href="https://www.facebook.com/"><img class="face" src="images/ico_facebook.png" alt="" /></a>
                    <a href="https://www.instagram.com"><img class="pic" src="images/ico_instagram.png" alt="" /></a>
                    <a href="https://twitter.com"><img class="pic" src="images/ico_twitter.png" alt="" /></a>
                </div>

                <select id="idiomas">
                    <option value="" disabled selected>Idiomas</option>
                    <option value="ingles">Inglês</option>
                    <option value="espanhol">Espanhol</option>
                    <option value="portugues">Português</option>
                    <option value="frances">Francês</option>
                    <option value="alemao">Alemão</option>
                    <option value="japones">Japones</option>
                </select>
            </div>
        </footer>
</body>

 <body>
        <ul class="bottom-menu">
        </ul>
        </div>
        </div>
        <script>
            $(function () {
                var box = $('.boxe');
                var menu = $('.top-menu')
                var button = $('.open-menu, .header-menu');
                button.on('click', function () {
                    box.toggleClass('active');
                    menu.toggleClass('active2');

                });
            });
        </script>
    </body>
</html>

Ponto Digital/Views/Shared/_Sucesso.cshtml
@{
var tipo = (string) ViewData["Tipo"];
var user = (string) ViewData["User"];
}

<head>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/site.min.css" />
</head>

<main>
    <h2>@ViewData["Controller"] com sucesso!</h2>
</main>